version: '3.8'

services:
  # Main development service
  knx-store-dev:
    build: .
    container_name: knx-store-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - astro_cache:/app/.astro
    ports:
      - "4001:4001"  # Astro dev server
      - "4002:4002"  # Alternative port
      - "4003:4003"  # API server
      - "4004:4004"  # Static file server
      - "6006:6006"  # Storybook
    working_dir: /app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - WORDPRESS_API_URL=${WORDPRESS_API_URL}
      - WOOCOMMERCE_API_URL=${WOOCOMMERCE_API_URL}
      - WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY}
      - WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GTM_ID=${GTM_ID:-GTM-XXXXXXX}
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"
    networks:
      - knx-network

  # WordPress API proxy (optional, for local development)
  wordpress-proxy:
    image: nginx:alpine
    container_name: wordpress-proxy
    ports:
      - "4005:80"
    volumes:
      - ./nginx/wordpress-proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - knx-network
    profiles:
      - proxy

  # Database for local development (optional)
  mysql-dev:
    image: mysql:8.0
    container_name: knx-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: knx_store_dev
      MYSQL_USER: knx_user
      MYSQL_PASSWORD: knx_password
    ports:
      - "4006:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - knx-network
    profiles:
      - database

  # Redis for caching (optional)
  redis-dev:
    image: redis:7-alpine
    container_name: knx-redis-dev
    ports:
      - "4007:6379"
    volumes:
      - redis_data:/data
    networks:
      - knx-network
    profiles:
      - cache

volumes:
  node_modules:
  astro_cache:
  mysql_data:
  redis_data:

networks:
  knx-network:
    driver: bridge
